const episodes = [
    { value: '', text: '/\\ Saison 2  /\\', disabled: true },
    { value: '43.jpg', text: '43# Spécial DnD - Part 4 - Célébration' },
    { value: '42.jpg', text: '42# Spécial DnD - Part 3 - Château de la mort' },
    { value: '41.jpg', text: '41# Spécial DnD - Part 2 - Le Pacte' },
    { value: '40.jpg', text: "40# Spécial DnD - Part 1 - L'aventure commence !" },
    { value: '39.jpg', text: '39# Halloween' },
    { value: '38.jpg', text: "38# Je t'aime" },
    { value: '37.jpg', text: "37# Je crois que je t'aime" },
    { value: '36.jpg', text: '36# Limite dépassée' },
    { value: '35.jpg', text: '35# Limite atteinte' },
    { value: '34.jpg', text: "34# Ray, l'Omniscient" },
    { value: '33.jpg', text: '33# Réception du colis à temps' },
    { value: '32.jpg', text: '32# Rival Blessé' },
    { value: '31.jpg', text: '31# Intervention' },
    { value: '30.jpg', text: '30# Spécial Roadtrip - Part 6 - Excellente compagnie' },
    { value: '29.jpg', text: '29# Spécial Roadtrip - Part 5 - Bonne compagnie' },
    { value: '28.jpg', text: '28# Spécial Roadtrip - Part 4 - Compagnie' },
    { value: '27.jpg', text: '27# Spécial Roadtrip - Part 3 - Bonne nuit' },
    { value: '26.jpg', text: '26# Spécial Roadtrip - Part 2 - Camping' },
    { value: '25.jpg', text: '25# Spécial Roadtrip - Part 1 - Roadtrip' },
    { value: '24.jpg', text: '24# En retard' },
    { value: '23.jpg', text: '23# Soirée entre potes - Part 2' },
    { value: '22.jpg', text: '22# Soirée entre potes - Part 1' },
    { value: '21.jpg', text: '21# Dev déteste' },
    { value: '20.jpg', text: '20# Pride - Part 2' },
    { value: '19.jpg', text: '19# Pride - Part 1' },
    { value: '18.jpg', text: '18# Escapade à la plage - Part 2' },
    { value: '17.jpg', text: '17# Escapade à la plage - Part 1' },
    { value: '16.jpg', text: '16# Brunch' },
    { value: '15.jpg', text: '15# Rivalité' },
    { value: '14.jpg', text: '14# Un ami' },
    { value: '13.jpg', text: '13# Expression Impassible' },
    { value: '12.jpg', text: '12# Partage de loisirs' },
    { value: '11.jpg', text: '11# I think I craft you' },
    { value: '10.jpg', text: '10# Jour pluvieux' },
    { value: '9.jpg', text: '9# Café' },
    { value: '8.jpg', text: '8# Sortie entre potes' },
    { value: '7.jpg', text: "7# Salut ! Moi, c'est..." },
    { value: '6.jpg', text: '6# Reste sur tes gardes' },
    { value: '5.jpg', text: '5# Quelle coïncidence!' },
    { value: '4.jpg', text: '4# Livraison retardée - Ça en valait la peine !' },
    { value: '3.jpg', text: '3# Évaluez votre livraison - Très insatisfait' },
    { value: '2.jpg', text: '2# Statut de livraison - de retour sur le planning' },
    { value: '1.jpg', text: '1# Livraison de colis' },
    { value: '', text: '/\\ Saison 1  /\\', disabled: true }
];