const episodes = [
    { value: '87.png', text: "87# Décisions", description: 'i think i like you VF episode 87 HD', url: '87' },
    { value: '86.png', text: "86# Seuil critique", description: 'i think i like you VF episode 86 HD', url: '86' },
    { value: '85.png', text: "85# Bandes blanchissantes", description: 'i think i like you VF episode 85 HD', url: '85' },
    { value: '84.png', text: "84# Trouvé", description: 'i think i like you VF episode 84 HD', url: '84' },
    { value: '', text: '/\\ Saison 3  /\\', description: 'i think i like you VF HD saison 3', disabled: true },
    { value: '83.png', text: "83# Amis", description: 'i think i like you VF episode 83 HD', url: '83' },
    { value: '82.png', text: "82# Promenade", description: 'i think i like you VF episode 82 HD', url: '82' },
    { value: '81.png', text: "81# Perdus et Retrouvés", description: 'i think i like you VF episode 81 HD', url: '81' },
    { value: '80.png', text: "80# Fin du voyage", description: 'i think i like you VF episode 80 HD', url: '80' },
    { value: '79.png', text: "79# La Mort de Sky", description: 'i think i like you VF episode 79 HD', url: '79' },
    { value: '78.png', text: "78# Tourtereaux", description: 'i think i like you VF episode 78 HD', url: '78' },
    { value: '77.png', text: "77# Merci", description: 'i think i like you VF episode 77 HD', url: '77' },
    { value: '76.png', text: "76# L'Intrus", description: 'i think i like you VF episode 76 HD', url: '76' },
    { value: '75.png', text: "75# Nouveau lieu", description: 'i think i like you VF episode 75 HD', url: '75' },
    { value: '74.png', text: "74# Résolution", description: 'i think i like you VF episode 74 HD', url: '74' },
    { value: '73.png', text: "73# Discussion", description: 'i think i like you VF episode 73 HD', url: '73' },
    { value: '72.png', text: "72# Écoute Red", description: 'i think i like you VF episode 72 HD', url: '72' },
    { value: '71.png', text: "71# Nouvel ami", description: 'i think i like you VF episode 71 HD', url: '71' },
    { value: '70.png', text: "70# Partenaire", description: 'i think i like you VF episode 70 HD', url: '70' },
    { value: '69.png', text: "69# Potes de muscu", description: 'i think i like you VF episode 69 HD', url: '69' },
    { value: '68.png', text: "68# Vérité", description: 'i think i like you VF episode 68 HD', url: '68' },
    { value: '67.png', text: "67# Amour fraternel", description: 'i think i like you VF episode 67 HD', url: '67' },
    { value: '66.png', text: "66# Courrier livré", description: 'i think i like you VF episode 66 HD', url: '66' },
    { value: '65.png', text: "65# Courrier reçu !", description: 'i think i like you VF episode 65 HD', url: '65' },
    { value: '64.png', text: "64# Je t'ai eu !", description: 'i think i like you VF episode 64 HD', url: '64' },
    { value: '63.png', text: "63# Le lendemain", description: 'i think i like you VF episode 63 HD', url: '63' },
    { value: '62.png', text: "62# Conneries Nocturnes", description: 'i think i like you VF episode 62 HD', url: '62' },
    { value: '61.png', text: "61# Prêteur sur gages 24h24", description: 'i think i like you VF episode 61 HD', url: '61' },
    { value: '60.png', text: "60# Double perception", description: 'i think i like you VF episode 60 HD', url: '60' },
    { value: '59.png', text: "59# Juste toi et moi", description: 'i think i like you VF episode 59 HD', url: '59' },
    { value: '58.png', text: "58# Crush", description: 'i think i like you VF episode 58', url: '58' },
    { value: '57.png', text: "57# Retour à la surface", description: 'i think i like you VF episode 57 HD', url: '57' },
    { value: '56.png', text: "56# L'Underground", description: 'i think i like you VF episode 56 HD', url: '56' },
    { value: '55.png', text: '55# Rencontrer et saluer', description: 'i think i like you VF episode 55 HD', url: '55' },
    { value: '54.png', text: '54# Nos chemins se recroisent', description: 'i think i like you VF episode 54 HD', url: '54' },
    { value: '53.png', text: '53# Bad boy', description: 'i think i like you VF episode 53 HD', url: '53' },
    { value: '52.png', text: '52# Crise existentielle', description: 'i think i like you VF episode 52 HD', url: '52' },
    { value: '51.png', text: '51# Tête-à-tête', description: 'i think i like you VF episode 51 HD', url: '51' },
    { value: '50.png', text: '50# Fais tes preuves', description: 'i think i like you VF episode 50 HD', url: '50' },
    { value: '49.png', text: '49# Fratrie', description: 'i think i like you VF episode 49 HD', url: '49' },
    { value: '48.png', text: '48# Urgence', description: 'i think i like you VF episode 48 HD', url: '48' },
    { value: '47.png', text: '47# Espionnage innocent', description: 'i think i like you VF episode 47 HD', url: '47' },
    { value: '46.png', text: '46# Protégé', description: 'i think i like you VF episode 46 HD', url: '46' },
    { value: '45.png', text: '45# Pas de cette façon', description: 'i think i like you VF episode 45 HD', url: '45' },
    { value: '44.png', text: '44# Je crois que je te connais', description: 'i think i like you VF episode 44 HD', url: '44' },
    { value: '', text: '/\\ Saison 2  /\\', description: 'i think i like you VF saison 2 HD', disabled: true },
    { value: '43.png', text: '43# Spécial DnD - Part 4 - Célébration', description: 'i think i like you VF episode 43 HD', url: '43' },
    { value: '42.png', text: '42# Spécial DnD - Part 3 - Château de la mort', description: 'i think i like you VF episode 4 HD2', url: '42' },
    { value: '41.png', text: '41# Spécial DnD - Part 2 - Le Pacte', description: 'i think i like you VF episode 41 HD', url: '41' },
    { value: '40.png', text: "40# Spécial DnD - Part 1 - L'aventure commence !", description: 'i think i like you VF episode 40 HD', url: '40' },
    { value: '39.png', text: '39# Halloween', description: 'i think i like you VF episode 39 HD', url: '39' },
    { value: '38.png', text: "38# Je t'aime", description: 'i think i like you VF episode 38 HD', url: '38' },
    { value: '37.png', text: "37# Je crois que je t'aime", description: 'i think i like you VF episode 37 HD', url: '37' },
    { value: '36.png', text: '36# Limite dépassée', description: 'i think i like you VF episode 36 HD', url: '36' },
    { value: '35.png', text: '35# Limite atteinte', description: 'i think i like you VF episode 35 HD', url: '35' },
    { value: '34.png', text: "34# Ray, l'Omniscient", description: 'i think i like you VF episode 34 HD', url: '34' },
    { value: '33.png', text: '33# Réception du colis à temps', description: 'i think i like you VF episode 33 HD', url: '33' },
    { value: '32.png', text: '32# Rival Blessé', description: 'i think i like you VF episode 32 HD', url: '32' },
    { value: '31.png', text: '31# Intervention', description: 'i think i like you VF episode 31 HD', url: '31' },
    { value: '30.png', text: '30# Spécial Roadtrip - Part 6 - Excellente compagnie', description: 'i think i like you VF episode 30 HD', url: '30' },
    { value: '29.png', text: '29# Spécial Roadtrip - Part 5 - Bonne compagnie', description: 'i think i like you VF episode 29 HD', url: '29' },
    { value: '28.png', text: '28# Spécial Roadtrip - Part 4 - Compagnie', description: 'i think i like you VF episode 28 HD', url: '28' },
    { value: '27.png', text: '27# Spécial Roadtrip - Part 3 - Bonne nuit', description: 'i think i like you VF episode 27 HD', url: '27' },
    { value: '26.png', text: '26# Spécial Roadtrip - Part 2 - Camping', description: 'i think i like you VF episode 26 HD', url: '26' },
    { value: '25.png', text: '25# Spécial Roadtrip - Part 1 - Roadtrip', description: 'i think i like you VF episode 25 HD', url: '25' },
    { value: '24.png', text: '24# En retard', description: 'i think i like you VF episode 24 HD', url: '24' },
    { value: '23.png', text: '23# Soirée entre potes - Part 2', description: 'i think i like you VF episode 23 HD', url: '23' },
    { value: '22.png', text: '22# Soirée entre potes - Part 1', description: 'i think i like you VF episode 22 HD', url: '22' },
    { value: '21.png', text: '21# Dev déteste', description: 'i think i like you VF episode 21 HD', url: '21' },
    { value: '20.png', text: '20# Pride - Part 2', description: 'i think i like you VF episode 20 HD', url: '20' },
    { value: '19.png', text: '19# Pride - Part 1', description: 'i think i like you VF episode 19 HD', url: '19' },
    { value: '18.png', text: '18# Escapade à la plage - Part 2', description: 'i think i like you VF episode 18 HD', url: '18' },
    { value: '17.png', text: '17# Escapade à la plage - Part 1', description: 'i think i like you VF episode 17 HD', url: '17' },
    { value: '16.png', text: '16# Brunch', description: 'i think i like you VF episode 16 HD', url: '16' },
    { value: '15.png', text: '15# Rivalité', description: 'i think i like you VF episode 15 HD', url: '15' },
    { value: '14.png', text: '14# Un ami', description: 'i think i like you VF episode 14 HD', url: '14' },
    { value: '13.png', text: '13# Expression Impassible', description: 'i think i like you VF episode 13 HD', url: '13' },
    { value: '12.png', text: '12# Partage de loisirs', description: 'i think i like you VF episode 12 HD', url: '12' },
    { value: '11.png', text: '11# I think I craft you', description: 'i think i like you VF episode 11 HD', url: '11' },
    { value: '10.png', text: '10# Jour pluvieux', description: 'i think i like you VF episode 10 HD', url: '10' },
    { value: '9.png', text: '9# Café', description: 'i think i like you VF episode 9 HD', url: '9' },
    { value: '8.png', text: '8# Sortie entre potes', description: 'i think i like you VF episode 8 HD', url: '8' },
    { value: '7.png', text: "7# Salut ! Moi, c'est...", description: 'i think i like you VF episode 7 HD', url: '7' },
    { value: '6.png', text: '6# Reste sur tes gardes', description: 'i think i like you VF episode 6 HD', url: '6' },
    { value: '5.png', text: '5# Quelle coïncidence!', description: 'i think i like you VF episode 5 HD', url: '5' },
    { value: '4.png', text: '4# Livraison retardée - Ça en valait la peine !', description: 'i think i like you VF episode 4 HD', url: '4' },
    { value: '3.png', text: '3# Évaluez votre livraison - Très insatisfait', description: 'i think i like you VF episode 3 HD', url: '3' },
    { value: '2.png', text: '2# Statut de livraison - de retour sur le planning', description: 'i think i like you VF episode 2 HD', url: '2' },
    { value: '1.png', text: '1# Livraison de colis', description: 'i think i like you VF episode 1 HD', url: '1' },
    { value: '', text: '/\\ Saison 1  /\\', description: 'i think i like you VF saison 1 HD', disabled: true }
];