const episodes = [
    {
        value: '115.png',
        text: '115# Petit ami protecteur',
        description: 'i think i like you VF episode 115 HD',
        url: ['115-1.png', '115-2.png'],
        multi: true
    },
    {
        value: '114.png',
        text: '114# Anubis',
        description: 'i think i like you VF episode 114 HD',
        url: ['114-1.png', '114-2.png'],
        multi: true
    },
    {
        value: '113.png',
        text: '113# Nouvelle région',
        description: 'i think i like you VF episode 113 HD',
        url: ['113-1.png', '113-2.png', '113-3.png'],
        multi: true
    },
    { value: '112.png', text: "112# Vote obtenu", description: 'i think i like you VF episode 112 HD', url: '112.png' },
    { value: 'polaroid111.webp', text: "Polaroid #111", description: 'i think i like you VF polaroid n°7', url: 'polaroid111.webp' },
    { value: '111.png', text: "111# Thé avec Cerbère", description: 'i think i like you VF episode 111 HD', url: '111.png' },
    { value: 'polaroid110.webp', text: "Polaroid #110", description: 'i think i like you VF polaroid n°6', url: 'polaroid110.webp' },
    { value: '110.png', text: "110# Malédictions", description: 'i think i like you VF episode 110 HD', url: '110.png' },
    { value: 'polaroid109.webp', text: "Polaroid #109", description: 'i think i like you VF polaroid n°5', url: 'polaroid109.webp' },
    { value: '109.png', text: "109# Cerbère", description: 'i think i like you VF episode 109 HD', url: '109.png' },
    { value: 'polaroid108.webp', text: "Polaroid #108", description: 'i think i like you VF polaroid n°4', url: 'polaroid108.webp' },
    {
        value: '108.png',
        text: '108# Nouvelle ville',
        description: 'i think i like you VF episode 108 HD',
        url: ['108-1.png', '108-2.png'],
        multi: true
    },
    { value: 'polaroid107.webp', text: "Polaroid #107", description: 'i think i like you VF polaroid n°3', url: 'polaroid107.webp' },
    { value: '107.png', text: "107# Procrastination", description: 'i think i like you VF episode 107 HD', url: '107.png' },
    { value: 'polaroid106.webp', text: "Polaroid #106", description: 'i think i like you VF polaroid n°2', url: 'polaroid106.webp' },
    {
        value: '106.png',
        text: '106# Le vrai voyage commence',
        description: 'i think i like you VF episode 106 HD',
        url: ['106-1.png', '106-2.png'],
        multi: true
    },
    { value: 'polaroid105.webp', text: "Polaroid #105", description: 'i think i like you VF polaroid n°1', url: 'polaroid105.webp' },
    { value: '105.png', text: "105# Réunion", description: 'i think i like you VF episode 105 HD', url: '105.png' },
    { value: '104.png', text: "104# Nous arrivons", description: 'i think i like you VF episode 104 HD', url: '104.png' },
    {
        value: '103.png',
        text: '103# Leshy',
        description: 'i think i like you VF episode 103 HD',
        url: ['103-1.png', '103-2.png'],
        multi: true
    },
    { value: '102.png', text: "102# Début du voyage", description: 'i think i like you VF episode 102 HD', url: '102.png' },
    { value: '101.png', text: "101# Descente", description: 'i think i like you VF episode 101 HD', url: '101.png' },
    { value: '100.png', text: "100# Bons amis", description: 'i think i like you VF episode 100 HD', url: '100.png' },
    { value: '99ff.png', text: "99# Fête foraine", description: 'i think i like you VF episode 99 HD', url: '99.png' },
    { value: '98ff.png', text: "98# Spot habituel", description: 'i think i like you VF episode 98 HD', url: '98.png' },
    { value: '97.png', text: "97# Pouvoirs", description: 'i think i like you VF episode 97 HD', url: '97.png' },
    { value: '96.png', text: "96# Et tu Brute", description: 'i think i like you VF episode 96 HD', url: '96.png' },
    { value: '95.png', text: "95# Inquiet", description: 'i think i like you VF episode 95 HD', url: '95.png' },
    { value: '94.png', text: "94# Rencontre", description: 'i think i like you VF episode 94 HD', url: '94.png' },
    { value: '93.png', text: "93# Virée nocturne", description: 'i think i like you VF episode 93 HD', url: '93.png' },
    { value: '92.png', text: "92# L'irrésistible Ray", description: 'i think i like you VF episode 92 HD', url: '92.png' },
    { value: '91.png', text: "91# Excès", description: 'i think i like you VF episode 91 HD', url: '91.png' },
    { value: '90.png', text: "90# Faire face", description: 'i think i like you VF episode 90 HD', url: '90.png' },
    { value: '89unblur.png', text: "89# Révélation", description: 'i think i like you VF episode 89 HD', url: '89.png' },
    { value: '88.png', text: "88# L'homme parfait pour ce job", description: 'i think i like you VF episode 88 HD', url: '88.png' },
    { value: '87.png', text: "87# Décisions", description: 'i think i like you VF episode 87 HD', url: '87.png' },
    { value: '86.png', text: "86# Seuil critique", description: 'i think i like you VF episode 86 HD', url: '86.png' },
    { value: '85.png', text: "85# Bandes blanchissantes", description: 'i think i like you VF episode 85 HD', url: '85.png' },
    { value: '84.png', text: "84# Trouvé", description: 'i think i like you VF episode 84 HD', url: '84.png' },
    { value: '', text: '/\\ Saison 3  /\\', description: 'i think i like you VF HD saison 3', disabled: true },
    { value: '83.png', text: "83# Amis", description: 'i think i like you VF episode 83 HD', url: '83.png' },
    { value: '82.png', text: "82# Promenade", description: 'i think i like you VF episode 82 HD', url: '82.png' },
    { value: '81.png', text: "81# Perdus et Retrouvés", description: 'i think i like you VF episode 81 HD', url: '81.png' },
    { value: '80.png', text: "80# Fin du voyage", description: 'i think i like you VF episode 80 HD', url: '80.png' },
    { value: '79.png', text: "79# La Mort de Sky", description: 'i think i like you VF episode 79 HD', url: '79.png' },
    { value: '78.png', text: "78# Tourtereaux", description: 'i think i like you VF episode 78 HD', url: '78.png' },
    { value: '77.png', text: "77# Merci", description: 'i think i like you VF episode 77 HD', url: '77.png' },
    { value: '76.png', text: "76# L'Intrus", description: 'i think i like you VF episode 76 HD', url: '76.png' },
    { value: '75.png', text: "75# Nouveau lieu", description: 'i think i like you VF episode 75 HD', url: '75.png' },
    { value: '74.png', text: "74# Résolution", description: 'i think i like you VF episode 74 HD', url: '74.png' },
    { value: '73.png', text: "73# Discussion", description: 'i think i like you VF episode 73 HD', url: '73.png' },
    { value: '72.png', text: "72# Écoute Red", description: 'i think i like you VF episode 72 HD', url: '72.png' },
    { value: '71.png', text: "71# Nouvel ami", description: 'i think i like you VF episode 71 HD', url: '71.png' },
    { value: '70.png', text: "70# Partenaire", description: 'i think i like you VF episode 70 HD', url: '70.png' },
    { value: '69.png', text: "69# Potes de muscu", description: 'i think i like you VF episode 69 HD', url: '69.png' },
    { value: '68.png', text: "68# Vérité", description: 'i think i like you VF episode 68 HD', url: '68.png' },
    { value: '67.png', text: "67# Amour fraternel", description: 'i think i like you VF episode 67 HD', url: '67.png' },
    { value: '66.png', text: "66# Courrier livré", description: 'i think i like you VF episode 66 HD', url: '66.png' },
    { value: '65.png', text: "65# Courrier reçu !", description: 'i think i like you VF episode 65 HD', url: '65.png' },
    { value: '64.png', text: "64# Je t'ai eu !", description: 'i think i like you VF episode 64 HD', url: '64.png' },
    { value: '63.png', text: "63# Le lendemain", description: 'i think i like you VF episode 63 HD', url: '63.png' },
    { value: '62.png', text: "62# Conneries Nocturnes", description: 'i think i like you VF episode 62 HD', url: '62.png' },
    { value: '61.png', text: "61# Prêteur sur gages 24h24", description: 'i think i like you VF episode 61 HD', url: '61.png' },
    { value: '60.png', text: "60# Double perception", description: 'i think i like you VF episode 60 HD', url: '60.png' },
    { value: '59.png', text: "59# Juste toi et moi", description: 'i think i like you VF episode 59 HD', url: '59.png' },
    { value: '58.png', text: "58# Crush", description: 'i think i like you VF episode 58', url: '58.png' },
    { value: '57.png', text: "57# Retour à la surface", description: 'i think i like you VF episode 57 HD', url: '57.png' },
    { value: '56.png', text: "56# L'Underground", description: 'i think i like you VF episode 56 HD', url: '56.png' },
    { value: '55.png', text: '55# Rencontrer et saluer', description: 'i think i like you VF episode 55 HD', url: '55.png' },
    { value: '54.png', text: '54# Nos chemins se recroisent', description: 'i think i like you VF episode 54 HD', url: '54.png' },
    { value: '53.png', text: '53# Bad boy', description: 'i think i like you VF episode 53 HD', url: '53.png' },
    { value: '52.png', text: '52# Crise existentielle', description: 'i think i like you VF episode 52 HD', url: '52.png' },
    { value: '51.png', text: '51# Tête-à-tête', description: 'i think i like you VF episode 51 HD', url: '51.png' },
    { value: '50.png', text: '50# Fais tes preuves', description: 'i think i like you VF episode 50 HD', url: '50.png' },
    { value: '49.png', text: '49# Fratrie', description: 'i think i like you VF episode 49 HD', url: '49.png' },
    { value: '48.png', text: '48# Urgence', description: 'i think i like you VF episode 48 HD', url: '48.png' },
    { value: '47.png', text: '47# Espionnage innocent', description: 'i think i like you VF episode 47 HD', url: '47.png' },
    { value: '46.png', text: '46# Protégé', description: 'i think i like you VF episode 46 HD', url: '46.png' },
    { value: '45.png', text: '45# Pas de cette façon', description: 'i think i like you VF episode 45 HD', url: '45.png' },
    { value: '44.png', text: '44# Je crois que je te connais', description: 'i think i like you VF episode 44 HD', url: '44.png' },
    { value: '', text: '/\\ Saison 2  /\\', description: 'i think i like you VF saison 2 HD', disabled: true },
    { value: '43.png', text: '43# Spécial DnD - Part 4 - Célébration', description: 'i think i like you VF episode 43 HD', url: '43.png' },
    { value: '42.png', text: '42# Spécial DnD - Part 3 - Château de la mort', description: 'i think i like you VF episode 4 HD', url: '42.png' },
    { value: '41.png', text: '41# Spécial DnD - Part 2 - Le Pacte', description: 'i think i like you VF episode 41 HD', url: '41.png' },
    { value: '40.png', text: "40# Spécial DnD - Part 1 - L'aventure commence !", description: 'i think i like you VF episode 40 HD', url: '40.png' },
    { value: '39.png', text: '39# Halloween', description: 'i think i like you VF episode 39 HD', url: '39.png' },
    { value: '38.png', text: "38# Je t'aime", description: 'i think i like you VF episode 38 HD', url: '38.png' },
    { value: '37.png', text: "37# Je crois que je t'aime", description: 'i think i like you VF episode 37 HD', url: '37.png' },
    { value: '36.png', text: '36# Limite dépassée', description: 'i think i like you VF episode 36 HD', url: '36.png' },
    { value: '35.png', text: '35# Limite atteinte', description: 'i think i like you VF episode 35 HD', url: '35.png' },
    { value: '34.png', text: "34# Ray, l'Omniscient", description: 'i think i like you VF episode 34 HD', url: '34.png' },
    { value: '33.png', text: '33# Réception du colis à temps', description: 'i think i like you VF episode 33 HD', url: '33.png' },
    { value: '32.png', text: '32# Rival Blessé', description: 'i think i like you VF episode 32 HD', url: '32.png' },
    { value: '31.png', text: '31# Intervention', description: 'i think i like you VF episode 31 HD', url: '31.png' },
    { value: '30.png', text: '30# Spécial Roadtrip - Part 6 - Excellente compagnie', description: 'i think i like you VF episode 30 HD', url: '30.png' },
    { value: '29.png', text: '29# Spécial Roadtrip - Part 5 - Bonne compagnie', description: 'i think i like you VF episode 29 HD', url: '29.png' },
    { value: '28.png', text: '28# Spécial Roadtrip - Part 4 - Compagnie', description: 'i think i like you VF episode 28 HD', url: '28.png' },
    { value: '27.png', text: '27# Spécial Roadtrip - Part 3 - Bonne nuit', description: 'i think i like you VF episode 27 HD', url: '27.png' },
    { value: '26.png', text: '26# Spécial Roadtrip - Part 2 - Camping', description: 'i think i like you VF episode 26 HD', url: '26.png' },
    { value: '25.png', text: '25# Spécial Roadtrip - Part 1 - Roadtrip', description: 'i think i like you VF episode 25 HD', url: '25.png' },
    { value: '24.png', text: '24# En retard', description: 'i think i like you VF episode 24 HD', url: '24.png' },
    { value: '23.png', text: '23# Soirée entre potes - Part 2', description: 'i think i like you VF episode 23 HD', url: '23.png' },
    { value: '22.png', text: '22# Soirée entre potes - Part 1', description: 'i think i like you VF episode 22 HD', url: '22.png' },
    { value: '21.png', text: '21# Dev déteste', description: 'i think i like you VF episode 21 HD', url: '21.png' },
    { value: '20.png', text: '20# Pride - Part 2', description: 'i think i like you VF episode 20 HD', url: '20.png' },
    { value: '19.png', text: '19# Pride - Part 1', description: 'i think i like you VF episode 19 HD', url: '19.png' },
    { value: '18.png', text: '18# Escapade à la plage - Part 2', description: 'i think i like you VF episode 18 HD', url: '18.png' },
    { value: '17.png', text: '17# Escapade à la plage - Part 1', description: 'i think i like you VF episode 17 HD', url: '17.png' },
    { value: '16.png', text: '16# Brunch', description: 'i think i like you VF episode 16 HD', url: '16.png' },
    { value: '15.png', text: '15# Rivalité', description: 'i think i like you VF episode 15 HD', url: '15.png' },
    { value: '14.png', text: '14# Un ami', description: 'i think i like you VF episode 14 HD', url: '14.png' },
    { value: '13.png', text: '13# Expression Impassible', description: 'i think i like you VF episode 13 HD', url: '13.png' },
    { value: '12.png', text: '12# Partage de loisirs', description: 'i think i like you VF episode 12 HD', url: '12.png' },
    { value: '11.png', text: '11# I think I craft you', description: 'i think i like you VF episode 11 HD', url: '11.png' },
    { value: '10.png', text: '10# Jour pluvieux', description: 'i think i like you VF episode 10 HD', url: '10.png' },
    { value: '9.png', text: '9# Café', description: 'i think i like you VF episode 9 HD', url: '9.png' },
    { value: '8.png', text: '8# Sortie entre potes', description: 'i think i like you VF episode 8 HD', url: '8.png' },
    { value: '7.png', text: "7# Salut ! Moi, c'est...", description: 'i think i like you VF episode 7 HD', url: '7.png' },
    { value: '6.png', text: '6# Reste sur tes gardes', description: 'i think i like you VF episode 6 HD', url: '6.png' },
    { value: '5.png', text: '5# Quelle coïncidence!', description: 'i think i like you VF episode 5 HD', url: '5.png' },
    { value: '4.png', text: '4# Livraison retardée - Ça en valait la peine !', description: 'i think i like you VF episode 4 HD', url: '4.png' },
    { value: '3.png', text: '3# Évaluez votre livraison - Très insatisfait', description: 'i think i like you VF episode 3 HD', url: '3.png' },
    { value: '2.png', text: '2# Statut de livraison - de retour sur le planning', description: 'i think i like you VF episode 2 HD', url: '2.png' },
    { value: '1.png', text: '1# Livraison de colis', description: 'i think i like you VF episode 1 HD', url: '1.png' },
    { value: '', text: '/\\ Saison 1  /\\', description: 'i think i like you VF saison 1 HD', disabled: true }
];