const episodes = [
    { value: '79.jpg', text: "79# La Mort de Sky", description: 'i think i like you VF episode 79', url: 'episode-79' },
    { value: '78.jpg', text: "78# Tourtereaux", description: 'i think i like you VF episode 78', url: 'episode-78' },
    { value: '77.jpg', text: "77# Merci", description: 'i think i like you VF episode 77', url: 'episode-77' },
    { value: '76.jpg', text: "76# L'Intrus", description: 'i think i like you VF episode 76', url: 'episode-76' },
    { value: '75.jpg', text: "75# Nouveau lieu", description: 'i think i like you VF episode 75', url: 'episode-75' },
    { value: '74.jpg', text: "74# Résolution", description: 'i think i like you VF episode 74', url: 'episode-74' },
    { value: '73.jpg', text: "73# Discussion", description: 'i think i like you VF episode 73', url: 'episode-73' },
    { value: '72.jpg', text: "72# Écoute Red", description: 'i think i like you VF episode 72', url: 'episode-72' },
    { value: '71.jpg', text: "71# Nouvel ami", description: 'i think i like you VF episode 71', url: 'episode-71' },
    { value: '70.jpg', text: "70# Partenaire", description: 'i think i like you VF episode 70', url: 'episode-70' },
    { value: '69.jpg', text: "69# Potes de muscu", description: 'i think i like you VF episode 69', url: 'episode-69' },
    { value: '68.jpg', text: "68# Vérité", description: 'i think i like you VF episode 68', url: 'episode-68' },
    { value: '67.jpg', text: "67# Amour fraternel", description: 'i think i like you VF episode 67', url: 'episode-67' },
    { value: '66.jpg', text: "66# Courrier livré", description: 'i think i like you VF episode 66', url: 'episode-66' },
    { value: '65.jpg', text: "65# Courrier reçu !", description: 'i think i like you VF episode 65', url: 'episode-65' },
    { value: '64.jpg', text: "64# Je t'ai eu !", description: 'i think i like you VF episode 64', url: 'episode-64' },
    { value: '63.jpg', text: "63# Le lendemain", description: 'i think i like you VF episode 63', url: 'episode-63' },
    { value: '62.jpg', text: "62# Conneries Nocturnes", description: 'i think i like you VF episode 62', url: 'episode-62' },
    { value: '61.jpg', text: "61# Prêteur sur gages 24h24", description: 'i think i like you VF episode 61', url: 'episode-61' },
    { value: '60.jpg', text: "60# Double perception", description: 'i think i like you VF episode 60', url: 'episode-60' },
    { value: '59.jpg', text: "59# Juste toi et moi", description: 'i think i like you VF episode 59', url: 'episode-59' },
    { value: '58.jpg', text: "58# Crush", description: 'i think i like you VF episode 58', url: 'episode-58' },
    { value: '57.jpg', text: "57# Retour à la surface", description: 'i think i like you VF episode 57', url: 'episode-57' },
    { value: '56.jpg', text: "56# L'Underground", description: 'i think i like you VF episode 56', url: 'episode-56' },
    { value: '55.jpg', text: '55# Rencontrer et saluer', description: 'i think i like you VF episode 55', url: 'episode-55' },
    { value: '54.jpg', text: '54# Nos chemins se recroisent', description: 'i think i like you VF episode 54', url: 'episode-54' },
    { value: '53.jpg', text: '53# Bad boy', description: 'i think i like you VF episode 53', url: 'episode-53' },
    { value: '52.jpg', text: '52# Crise existentielle', description: 'i think i like you VF episode 52', url: 'episode-52' },
    { value: '51.jpg', text: '51# Tête-à-tête', description: 'i think i like you VF episode 51', url: 'episode-51' },
    { value: '50.jpg', text: '50# Fais tes preuves', description: 'i think i like you VF episode 50', url: 'episode-50' },
    { value: '49.jpg', text: '49# Fratrie', description: 'i think i like you VF episode 49', url: 'episode-49' },
    { value: '48.jpg', text: '48# Urgence', description: 'i think i like you VF episode 48', url: 'episode-48' },
    { value: '47.jpg', text: '47# Espionnage innocent', description: 'i think i like you VF episode 47', url: 'episode-47' },
    { value: '46.jpg', text: '46# Protégé', description: 'i think i like you VF episode 46', url: 'episode-46' },
    { value: '45.jpg', text: '45# Pas de cette façon', description: 'i think i like you VF episode 45', url: 'episode-45' },
    { value: '44.jpg', text: '44# Je crois que je te connais', description: 'i think i like you VF episode 44', url: 'episode-44' },
    { value: '', text: '/\\ Saison 2  /\\', description: 'i think i like you VF saison 2', disabled: true },
    { value: '43.jpg', text: '43# Spécial DnD - Part 4 - Célébration', description: 'i think i like you VF episode 43', url: 'episode-43' },
    { value: '42.jpg', text: '42# Spécial DnD - Part 3 - Château de la mort', description: 'i think i like you VF episode 42', url: 'episode-42' },
    { value: '41.jpg', text: '41# Spécial DnD - Part 2 - Le Pacte', description: 'i think i like you VF episode 41', url: 'episode-41' },
    { value: '40.jpg', text: "40# Spécial DnD - Part 1 - L'aventure commence !", description: 'i think i like you VF episode 40', url: 'episode-40' },
    { value: '39.jpg', text: '39# Halloween', description: 'i think i like you VF episode 39', url: 'episode-39' },
    { value: '38.jpg', text: "38# Je t'aime", description: 'i think i like you VF episode 38', url: 'episode-38' },
    { value: '37.jpg', text: "37# Je crois que je t'aime", description: 'i think i like you VF episode 37', url: 'episode-37' },
    { value: '36.jpg', text: '36# Limite dépassée', description: 'i think i like you VF episode 36', url: 'episode-36' },
    { value: '35.jpg', text: '35# Limite atteinte', description: 'i think i like you VF episode 35', url: 'episode-35' },
    { value: '34.jpg', text: "34# Ray, l'Omniscient", description: 'i think i like you VF episode 34', url: 'episode-34' },
    { value: '33.jpg', text: '33# Réception du colis à temps', description: 'i think i like you VF episode 33', url: 'episode-33' },
    { value: '32.jpg', text: '32# Rival Blessé', description: 'i think i like you VF episode 32', url: 'episode-32' },
    { value: '31.jpg', text: '31# Intervention', description: 'i think i like you VF episode 31', url: 'episode-31' },
    { value: '30.jpg', text: '30# Spécial Roadtrip - Part 6 - Excellente compagnie', description: 'i think i like you VF episode 30', url: 'episode-30' },
    { value: '29.jpg', text: '29# Spécial Roadtrip - Part 5 - Bonne compagnie', description: 'i think i like you VF episode 29', url: 'episode-29' },
    { value: '28.jpg', text: '28# Spécial Roadtrip - Part 4 - Compagnie', description: 'i think i like you VF episode 28', url: 'episode-28' },
    { value: '27.jpg', text: '27# Spécial Roadtrip - Part 3 - Bonne nuit', description: 'i think i like you VF episode 27', url: 'episode-27' },
    { value: '26.jpg', text: '26# Spécial Roadtrip - Part 2 - Camping', description: 'i think i like you VF episode 26', url: 'episode-26' },
    { value: '25.jpg', text: '25# Spécial Roadtrip - Part 1 - Roadtrip', description: 'i think i like you VF episode 25', url: 'episode-25' },
    { value: '24.jpg', text: '24# En retard', description: 'i think i like you VF episode 24', url: 'episode-24' },
    { value: '23.jpg', text: '23# Soirée entre potes - Part 2', description: 'i think i like you VF episode 23', url: 'episode-23' },
    { value: '22.jpg', text: '22# Soirée entre potes - Part 1', description: 'i think i like you VF episode 22', url: 'episode-22' },
    { value: '21.jpg', text: '21# Dev déteste', description: 'i think i like you VF episode 21', url: 'episode-21' },
    { value: '20.jpg', text: '20# Pride - Part 2', description: 'i think i like you VF episode 20', url: 'episode-20' },
    { value: '19.jpg', text: '19# Pride - Part 1', description: 'i think i like you VF episode 19', url: 'episode-19' },
    { value: '18.jpg', text: '18# Escapade à la plage - Part 2', description: 'i think i like you VF episode 18', url: 'episode-18' },
    { value: '17.jpg', text: '17# Escapade à la plage - Part 1', description: 'i think i like you VF episode 17', url: 'episode-17' },
    { value: '16.jpg', text: '16# Brunch', description: 'i think i like you VF episode 16', url: 'episode-16' },
    { value: '15.jpg', text: '15# Rivalité', description: 'i think i like you VF episode 15', url: 'episode-15' },
    { value: '14.jpg', text: '14# Un ami', description: 'i think i like you VF episode 14', url: 'episode-14' },
    { value: '13.jpg', text: '13# Expression Impassible', description: 'i think i like you VF episode 13', url: 'episode-13' },
    { value: '12.jpg', text: '12# Partage de loisirs', description: 'i think i like you VF episode 12', url: 'episode-12' },
    { value: '11.jpg', text: '11# I think I craft you', description: 'i think i like you VF episode 11', url: 'episode-11' },
    { value: '10.jpg', text: '10# Jour pluvieux', description: 'i think i like you VF episode 10', url: 'episode-10' },
    { value: '9.jpg', text: '9# Café', description: 'i think i like you VF episode 9', url: 'episode-9' },
    { value: '8.jpg', text: '8# Sortie entre potes', description: 'i think i like you VF episode 8', url: 'episode-8' },
    { value: '7.jpg', text: "7# Salut ! Moi, c'est...", description: 'i think i like you VF episode 7', url: 'episode-7' },
    { value: '6.jpg', text: '6# Reste sur tes gardes', description: 'i think i like you VF episode 6', url: 'episode-6' },
    { value: '5.jpg', text: '5# Quelle coïncidence!', description: 'i think i like you VF episode 5', url: 'episode-5' },
    { value: '4.jpg', text: '4# Livraison retardée - Ça en valait la peine !', description: 'i think i like you VF episode 4', url: 'episode-4' },
    { value: '3.jpg', text: '3# Évaluez votre livraison - Très insatisfait', description: 'i think i like you VF episode 3', url: 'episode-3' },
    { value: '2.jpg', text: '2# Statut de livraison - de retour sur le planning', description: 'i think i like you VF episode 2', url: 'episode-2' },
    { value: '1.jpg', text: '1# Livraison de colis', description: 'i think i like you VF episode 1', url: 'episode-1' },
    { value: '', text: '/\\ Saison 1  /\\', description: 'i think i like you VF saison 1', disabled: true }
];