const episodes = [
    { value: '107.jpg', text: "107# Procrastination", description: 'i think i like you VF episode 107', url: '107.jpg' },
    { value: 'polaroid106.webp', text: "Polaroid #106", description: 'i think i like you VF polaroid n°2', url: 'polaroid106.webp' },
    {
        value: '106.jpg',
        text: '106# Le vrai voyage commence',
        description: 'i think i like you VF episode 106',
        url: ['106-1.jpg', '106-2.jpg'],
        multi: true
    },
    { value: 'polaroid105.webp', text: "Polaroid #105", description: 'i think i like you VF polaroid n°1', url: 'polaroid105.webp' },
    { value: '105.jpg', text: "105# Réunion", description: 'i think i like you VF episode 105', url: '105.jpg' },
    { value: '104.jpg', text: "104# Nous arrivons", description: 'i think i like you VF episode 104', url: '104.jpg' },
    {
        value: '103.jpg',
        text: '103# Leshy',
        description: 'i think i like you VF episode 103',
        url: ['103-1.jpg', '103-2.jpg'],
        multi: true
    },
    {
        value: '102.jpg',
        text: '102# Début du voyage',
        description: 'i think i like you VF episode 102',
        url: ['102-1.jpg', '102-2.jpg'],
        multi: true
    },
    {
        value: '101.jpg',
        text: '101# Descente',
        description: 'i think i like you VF episode 101',
        url: ['101-1.jpg', '101-2.jpg'],
        multi: true
    },
    { value: '100.jpg', text: "100# Bons amis", description: 'i think i like you VF episode 100', url: '100.jpg' },
    { value: '99ff.jpg', text: "99# Fête foraine", description: 'i think i like you VF episode 99', url: '99.jpg' },
    { value: '98ff.jpg', text: "98# Spot habituel", description: 'i think i like you VF episode 98', url: '98.jpg' },
    { value: '97.jpg', text: "97# Pouvoirs", description: 'i think i like you VF episode 97', url: '97.jpg' },
    { value: '96.jpg', text: "96# Et tu Brute", description: 'i think i like you VF episode 96', url: '96.jpg' },
    { value: '95.jpg', text: "95# Inquiet", description: 'i think i like you VF episode 95', url: '95.jpg' },
    { value: '94.jpg', text: "94# Rencontre", description: 'i think i like you VF episode 94', url: '94.jpg' },
    { value: '93.jpg', text: "93# Virée nocturne", description: 'i think i like you VF episode 93', url: '93.jpg' },
    { value: '92.jpg', text: "92# L'irrésistible Ray", description: 'i think i like you VF episode 92', url: '92.jpg' },
    { value: '91.jpg', text: "91# Excès", description: 'i think i like you VF episode 91', url: '91.jpg' },
    { value: '90.jpg', text: "90# Faire face", description: 'i think i like you VF episode 90', url: '90.jpg' },
    { value: '89unblur.jpg', text: "89# Révélation", description: 'i think i like you VF episode 89', url: '89.jpg' },
    { value: '88.jpg', text: "88# L'homme parfait pour ce job", description: 'i think i like you VF episode 88', url: '88.jpg' },
    { value: '87.jpg', text: "87# Décisions", description: 'i think i like you VF episode 87', url: '87.jpg' },
    { value: '86.jpg', text: "86# Seuil critique", description: 'i think i like you VF episode 86', url: '86.jpg' },
    { value: '85.jpg', text: "85# Bandes blanchissantes", description: 'i think i like you VF episode 85', url: '85.jpg' },
    { value: '84.jpg', text: "84# Trouvé", description: 'i think i like you VF episode 84', url: '84.jpg' },
    { value: '', text: '/\\ Saison 3  /\\', description: 'i think i like you VF HD saison 3', disabled: true },
    { value: '83.jpg', text: "83# Amis", description: 'i think i like you VF episode 83', url: '83.jpg' },
    { value: '82.jpg', text: "82# Promenade", description: 'i think i like you VF episode 82', url: '82.jpg' },
    { value: '81.jpg', text: "81# Perdus et Retrouvés", description: 'i think i like you VF episode 81', url: '81.jpg' },
    { value: '80.jpg', text: "80# Fin du voyage", description: 'i think i like you VF episode 80', url: '80.jpg' },
    { value: '79.jpg', text: "79# La Mort de Sky", description: 'i think i like you VF episode 79', url: '79.jpg' },
    { value: '78.jpg', text: "78# Tourtereaux", description: 'i think i like you VF episode 78', url: '78.jpg' },
    { value: '77.jpg', text: "77# Merci", description: 'i think i like you VF episode 77', url: '77.jpg' },
    { value: '76.jpg', text: "76# L'Intrus", description: 'i think i like you VF episode 76', url: '76.jpg' },
    { value: '75.jpg', text: "75# Nouveau lieu", description: 'i think i like you VF episode 75', url: '75.jpg' },
    { value: '74.jpg', text: "74# Résolution", description: 'i think i like you VF episode 74', url: '74.jpg' },
    { value: '73.jpg', text: "73# Discussion", description: 'i think i like you VF episode 73', url: '73.jpg' },
    { value: '72.jpg', text: "72# Écoute Red", description: 'i think i like you VF episode 72', url: '72.jpg' },
    { value: '71.jpg', text: "71# Nouvel ami", description: 'i think i like you VF episode 71', url: '71.jpg' },
    { value: '70.jpg', text: "70# Partenaire", description: 'i think i like you VF episode 70', url: '70.jpg' },
    { value: '69.jpg', text: "69# Potes de muscu", description: 'i think i like you VF episode 69', url: '69.jpg' },
    { value: '68.jpg', text: "68# Vérité", description: 'i think i like you VF episode 68', url: '68.jpg' },
    { value: '67.jpg', text: "67# Amour fraternel", description: 'i think i like you VF episode 67', url: '67.jpg' },
    { value: '66.jpg', text: "66# Courrier livré", description: 'i think i like you VF episode 66', url: '66.jpg' },
    { value: '65.jpg', text: "65# Courrier reçu !", description: 'i think i like you VF episode 65', url: '65.jpg' },
    { value: '64.jpg', text: "64# Je t'ai eu !", description: 'i think i like you VF episode 64', url: '64.jpg' },
    { value: '63.jpg', text: "63# Le lendemain", description: 'i think i like you VF episode 63', url: '63.jpg' },
    { value: '62.jpg', text: "62# Conneries Nocturnes", description: 'i think i like you VF episode 62', url: '62.jpg' },
    { value: '61.jpg', text: "61# Prêteur sur gages 24h24", description: 'i think i like you VF episode 61', url: '61.jpg' },
    { value: '60.jpg', text: "60# Double perception", description: 'i think i like you VF episode 60', url: '60.jpg' },
    { value: '59.jpg', text: "59# Juste toi et moi", description: 'i think i like you VF episode 59', url: '59.jpg' },
    { value: '58.jpg', text: "58# Crush", description: 'i think i like you VF episode 58', url: '58.jpg' },
    { value: '57.jpg', text: "57# Retour à la surface", description: 'i think i like you VF episode 57', url: '57.jpg' },
    { value: '56.jpg', text: "56# L'Underground", description: 'i think i like you VF episode 56', url: '56.jpg' },
    { value: '55.jpg', text: '55# Rencontrer et saluer', description: 'i think i like you VF episode 55', url: '55.jpg' },
    { value: '54.jpg', text: '54# Nos chemins se recroisent', description: 'i think i like you VF episode 54', url: '54.jpg' },
    { value: '53.jpg', text: '53# Bad boy', description: 'i think i like you VF episode 53', url: '53.jpg' },
    { value: '52.jpg', text: '52# Crise existentielle', description: 'i think i like you VF episode 52', url: '52.jpg' },
    { value: '51.jpg', text: '51# Tête-à-tête', description: 'i think i like you VF episode 51', url: '51.jpg' },
    { value: '50.jpg', text: '50# Fais tes preuves', description: 'i think i like you VF episode 50', url: '50.jpg' },
    { value: '49.jpg', text: '49# Fratrie', description: 'i think i like you VF episode 49', url: '49.jpg' },
    { value: '48.jpg', text: '48# Urgence', description: 'i think i like you VF episode 48', url: '48.jpg' },
    { value: '47.jpg', text: '47# Espionnage innocent', description: 'i think i like you VF episode 47', url: '47.jpg' },
    { value: '46.jpg', text: '46# Protégé', description: 'i think i like you VF episode 46', url: '46.jpg' },
    { value: '45.jpg', text: '45# Pas de cette façon', description: 'i think i like you VF episode 45', url: '45.jpg' },
    { value: '44.jpg', text: '44# Je crois que je te connais', description: 'i think i like you VF episode 44', url: '44.jpg' },
    { value: '', text: '/\\ Saison 2  /\\', description: 'i think i like you VF saison 2', disabled: true },
    { value: '43.jpg', text: '43# Spécial DnD - Part 4 - Célébration', description: 'i think i like you VF episode 43', url: '43.jpg' },
    { value: '42.jpg', text: '42# Spécial DnD - Part 3 - Château de la mort', description: 'i think i like you VF episode 42', url: '42.jpg' },
    { value: '41.jpg', text: '41# Spécial DnD - Part 2 - Le Pacte', description: 'i think i like you VF episode 41', url: '41.jpg' },
    { value: '40.jpg', text: "40# Spécial DnD - Part 1 - L'aventure commence !", description: 'i think i like you VF episode 40', url: '40.jpg' },
    { value: '39.jpg', text: '39# Halloween', description: 'i think i like you VF episode 39', url: '39.jpg' },
    { value: '38.jpg', text: "38# Je t'aime", description: 'i think i like you VF episode 38', url: '38.jpg' },
    { value: '37.jpg', text: "37# Je crois que je t'aime", description: 'i think i like you VF episode 37', url: '37.jpg' },
    { value: '36.jpg', text: '36# Limite dépassée', description: 'i think i like you VF episode 36', url: '36.jpg' },
    { value: '35.jpg', text: '35# Limite atteinte', description: 'i think i like you VF episode 35', url: '35.jpg' },
    { value: '34.jpg', text: "34# Ray, l'Omniscient", description: 'i think i like you VF episode 34', url: '34.jpg' },
    { value: '33.jpg', text: '33# Réception du colis à temps', description: 'i think i like you VF episode 33', url: '33.jpg' },
    { value: '32.jpg', text: '32# Rival Blessé', description: 'i think i like you VF episode 32', url: '32.jpg' },
    { value: '31.jpg', text: '31# Intervention', description: 'i think i like you VF episode 31', url: '31.jpg' },
    { value: '30.jpg', text: '30# Spécial Roadtrip - Part 6 - Excellente compagnie', description: 'i think i like you VF episode 30', url: '30.jpg' },
    { value: '29.jpg', text: '29# Spécial Roadtrip - Part 5 - Bonne compagnie', description: 'i think i like you VF episode 29', url: '29.jpg' },
    { value: '28.jpg', text: '28# Spécial Roadtrip - Part 4 - Compagnie', description: 'i think i like you VF episode 28', url: '28.jpg' },
    { value: '27.jpg', text: '27# Spécial Roadtrip - Part 3 - Bonne nuit', description: 'i think i like you VF episode 27', url: '27.jpg' },
    { value: '26.jpg', text: '26# Spécial Roadtrip - Part 2 - Camping', description: 'i think i like you VF episode 26', url: '26.jpg' },
    { value: '25.jpg', text: '25# Spécial Roadtrip - Part 1 - Roadtrip', description: 'i think i like you VF episode 25', url: '25.jpg' },
    { value: '24.jpg', text: '24# En retard', description: 'i think i like you VF episode 24', url: '24.jpg' },
    { value: '23.jpg', text: '23# Soirée entre potes - Part 2', description: 'i think i like you VF episode 23', url: '23.jpg' },
    { value: '22.jpg', text: '22# Soirée entre potes - Part 1', description: 'i think i like you VF episode 22', url: '22.jpg' },
    { value: '21.jpg', text: '21# Dev déteste', description: 'i think i like you VF episode 21', url: '21.jpg' },
    { value: '20.jpg', text: '20# Pride - Part 2', description: 'i think i like you VF episode 20', url: '20.jpg' },
    { value: '19.jpg', text: '19# Pride - Part 1', description: 'i think i like you VF episode 19', url: '19.jpg' },
    { value: '18.jpg', text: '18# Escapade à la plage - Part 2', description: 'i think i like you VF episode 18', url: '18.jpg' },
    { value: '17.jpg', text: '17# Escapade à la plage - Part 1', description: 'i think i like you VF episode 17', url: '17.jpg' },
    { value: '16.jpg', text: '16# Brunch', description: 'i think i like you VF episode 16', url: '16.jpg' },
    { value: '15.jpg', text: '15# Rivalité', description: 'i think i like you VF episode 15', url: '15.jpg' },
    { value: '14.jpg', text: '14# Un ami', description: 'i think i like you VF episode 14', url: '14.jpg' },
    { value: '13.jpg', text: '13# Expression Impassible', description: 'i think i like you VF episode 13', url: '13.jpg' },
    { value: '12.jpg', text: '12# Partage de loisirs', description: 'i think i like you VF episode 12', url: '12.jpg' },
    { value: '11.jpg', text: '11# I think I craft you', description: 'i think i like you VF episode 11', url: '11.jpg' },
    { value: '10.jpg', text: '10# Jour pluvieux', description: 'i think i like you VF episode 10', url: '10.jpg' },
    { value: '9.jpg', text: '9# Café', description: 'i think i like you VF episode 9', url: '9.jpg' },
    { value: '8.jpg', text: '8# Sortie entre potes', description: 'i think i like you VF episode 8', url: '8.jpg' },
    { value: '7.jpg', text: "7# Salut ! Moi, c'est...", description: 'i think i like you VF episode 7', url: '7.jpg' },
    { value: '6.jpg', text: '6# Reste sur tes gardes', description: 'i think i like you VF episode 6', url: '6.jpg' },
    { value: '5.jpg', text: '5# Quelle coïncidence!', description: 'i think i like you VF episode 5', url: '5.jpg' },
    { value: '4.jpg', text: '4# Livraison retardée - Ça en valait la peine !', description: 'i think i like you VF episode 4', url: '4.jpg' },
    { value: '3.jpg', text: '3# Évaluez votre livraison - Très insatisfait', description: 'i think i like you VF episode 3', url: '3.jpg' },
    { value: '2.jpg', text: '2# Statut de livraison - de retour sur le planning', description: 'i think i like you VF episode 2', url: '2.jpg' },
    { value: '1.jpg', text: '1# Livraison de colis', description: 'i think i like you VF episode 1', url: '1.jpg' },
    { value: '', text: '/\\ Saison 1  /\\', description: 'i think i like you VF saison 1', disabled: true }
];